### ISSUE TITLE
Seems like it has no internet connection

### ISSUE THREAD

**Issue by ShonP40** [MFDGaming/Ubuntu-In-Ish#1]
When I try to do `apt-get update` it fails to download anything.
I tried changing the nameserver and replacing the sources list and nothing works.

So is there a way to get it to connect to the internet?

**Comment by econcz** [comment]
/etc/resolv.conf was not copied into chroot

**Comment by ShonP40** [comment]
It was
And even if I change the DNS servers in it manually, it's still not going to connect.

**Comment by ShonP40** [comment]
Probably never going to be fixed
